export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SET_KEYWORD = "SET_KEYWORD";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
